fastlane_version "2.98.0"
default_platform :ios

platform :ios do
  desc "Manual deploy to testflight"
  lane :manual_testflight do
    match(
      type: "appstore",
      readonly: true,
      git_url: "git@github.com:diego3g/deployrn-certs.git"
    )

    increment_build_number(
      xcodeproj: "./deployrn.xcodeproj"
    )

    build_app(
      workspace: "deployrn.xcworkspace",
      configuration: "Release",
      scheme: "deployrn"
    )

    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end

  desc "Automatic deploy to testflight"
  lane :ci_testflight do
    create_keychain(
      name: "actiontest_keychain",
      password: "citest",
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: false
    )

    match(
      git_url: "https://diego3g:#{ENV["CI_TOKEN"]}@github.com/diego3g/deployrn-certs.git",
      keychain_name: "actiontest_keychain",
      keychain_password: "citest",
      readonly: is_ci,
      type: "appstore"
    )

    increment_build_number(
      xcodeproj: "./deployrn.xcodeproj"
    )
 
    add_badge

    build_app(
      workspace: "deployrn.xcworkspace",
      scheme: "deployrn",
      export_method: "app-store",
      build_path: "./builds",
      output_directory: "./builds"
    )

    commit_version_bump(
      message: "Version Bump"
    )

    upload_to_testflight(
      username: "ci@rocketseat.dev",
      skip_waiting_for_build_processing: true
    )

    delete_keychain(
      name: "actiontest_keychain"
    )
  end
end
